### ISSUE TITLE
Failed to generate Prisma Client when using pnpm and specific dependency configurations

### ISSUE THREAD

**Issue by YangFong** [prisma/nuxt-prisma#49]
Hello Prisma team,

I'm encountering an issue with Prisma Client generation in a Nuxt project. Here's a summary of the situation and the findings so far:

### Problem

When trying to generate the Prisma Client, I receive the following error:

```
Failed to generate Prisma Client.
```

### Findings

After some investigation and testing, here are the conclusions I've drawn:

- **pnpm compatibility issue:** The issue only occurs when using `pnpm`. Switching to `npm` resolves it.
- **Dependency placement:** Both `@prisma/nuxt` and `nuxt` must be listed under `dependencies`. If either of them is placed in `devDependencies`, the error is triggered.

### Impact
This issue has been quite confusing and time-consuming for me—I've spent around two days diagnosing it. The error behavior feels unexpected, and it's not clear why these specific conditions would cause Prisma Client generation to fail.

### Question
Could you help clarify why this might be happening? Is it a known limitation or a bug that needs addressing?

Thank you for your time and help!

> I used AI to generate the above description

### Versions

```json
{
  "dependencies": {
    "@prisma/nuxt": "^0.0.35",
    "nuxt": "^3.14.0"
  },
  "devDependencies": {
    "@prisma/client": "^5.22.0",
    "prisma": "5.22.0",
    "vue": "latest",
    "vue-router": "latest"
  }
}
```

**Comment by ankur-arch** [comment]
Hey @YangFong , thanks for reporting the issue. Could you enable debugging and share the output?

https://www.prisma.io/docs/orm/prisma-client/debugging-and-troubleshooting/debugging#setting-the-debug-environment-variable

**Comment by YangFong** [comment]
I'm not sure if this is the right move.

package.json:

```json
{
  "devDependencies": {
    "@prisma/client": "^5.22.0",
    "@prisma/nuxt": "^0.0.35",
    "nuxt": "^3.14.0",
    "prisma": "^5.22.0",
    "vue": "latest",
    "vue-router": "latest"
  }
}
```

output:

```sh
❯ DEBUG="prisma*" npm run build       

> build
> nuxt build

Nuxt 3.14.159 with Nitro 2.10.3                                                                                                                                  17:38:27
[nuxt] modules:before: 0.195ms                                                                                                                                   17:38:28
[nuxt] kit:compatibility: 9.343ms                                                                                                                                17:38:28
[nuxt] kit:compatibility: 9.439ms                                                                                                                                17:38:28
[nuxt] kit:compatibility: 9.545ms                                                                                                                                17:38:28
[nuxt] kit:compatibility: 9.521ms                                                                                                                                17:38:28
[nuxt] kit:compatibility: 9.725ms                                                                                                                                17:38:28
[nuxt] kit:compatibility: 9.946ms                                                                                                                                17:38:28
[nuxt] kit:compatibility: 10.094ms                                                                                                                               17:38:28
[nuxt] kit:compatibility: 10.405ms                                                                                                                               17:38:28
[nuxt] kit:compatibility: 10.767ms                                                                                                                               17:38:28
[nuxt] kit:compatibility: 10.854ms                                                                                                                               17:38:28
[nuxt] kit:compatibility: 11.031ms                                                                                                                               17:38:28
✔ Prisma CLI is already installed.                                                                                                                              17:38:32
✔ Prisma schema file exists.                                                                                                                                    17:38:32
✔ Database migrations folder exists.                                                                                                                            17:38:32
                                                                                                                                                                 17:38:32
Not migrating the database.
Generating Prisma client...                                                                                                                                      17:38:32


 ERROR  ✘ Failed to generate Prisma Client.                                                                                                                      17:38:45


Skipped installing Prisma Studio.                                                                                                                                17:38:45
[nuxt] kit:compatibility: 0.162ms                                                                                                                                17:38:45

 WARN  Slow module @prisma/nuxt took 17443.7ms to setup.                                                                                                         17:38:45


 ERROR  Nuxt module should be a function: @nuxt/devtools                                                                                                         17:38:45

  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2460:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4669:5)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:4839:5)
  at async Module.loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2627:19)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:77:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7) 



 ERROR  Nuxt module should be a function: @nuxt/devtools                                                                                                         17:38:45

```

**Comment by ankur-arch** [comment]
Thanks for getting back to me. I'll tackle this next week, also I think it's related to #47 .  Let's continue the discussion there.
